export const DO_SIGNIN = 'DO_SIGNIN';
export const DO_SIGNIN_SUCCESS = 'DO_SIGNIN_SUCCESS';
export const DO_SIGNIN_FAILURE = 'DO_SIGNIN_FAILURE';

export const DO_SIGNOUT = 'DO_SIGNOUT';
export const DO_SIGNOUT_SUCCESS = 'DO_SIGNOUT_SUCCESS';
export const DO_SIGNOUT_FAILURE = 'DO_SIGNOUT_FAILURE';