export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

export const LOAD_OWN_JOBS = 'LOAD_OWN_JOBS';
export const LOAD_OWN_JOBS_SUCCESS = 'LOAD_OWN_JOBS_SUCCESS';
export const LOAD_OWN_JOBS_FAILURE = 'LOAD_OWN_JOBS_FAILURE';